# Generated by Django 4.0 on 2022-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('dialog_id', models.IntegerField()),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=2)),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
    ]
