name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Start docker stack
        run: docker-compose up --build -d

      - name: Wait a little bit
        run: sleep 5

      - name: Running migrations (testing readme)
        run: docker-compose exec -T web python manage.py migrate

      - name: Running tests
        run: |
          docker-compose exec -T web python manage.py test -v2
      - name: Docker compose logs (hopefully showing failure)
        if: failure()
        run: docker-compose logs
